# Generated by Django 4.2.1 on 2023-05-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=225)),
                ('reference_author', models.CharField(max_length=225)),
                ('aliquot_date', models.DateField()),
                ('reagent', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Protocol',
                'db_table': 'protocols',
            },
        ),
    ]
