# Generated by Django 4.2.1 on 2023-05-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='flow',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='protocolprocess',
            name='value',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
