# Generated by Django 4.2.1 on 2023-05-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='aliquot_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='description',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='reagent',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='reference_author',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
