# Generated by Django 4.2.1 on 2023-05-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_alter_protocol_aliquot_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
