# Generated by Django 4.2.1 on 2023-05-25 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0003_protocolnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_node_edges', to='protocols.protocolnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_node_edges', to='protocols.protocolnode')),
            ],
            options={
                'verbose_name': 'ProtocolEdge',
                'db_table': 'protocol_edges',
            },
        ),
    ]
