# Generated by Django 4.2.1 on 2023-05-25 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_remove_ingredients_unit'),
        ('protocols', '0004_protocoledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=225)),
                ('quantity', models.FloatField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_ingredient', to='ingredients.ingredients')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_ingredient', to='protocols.protocol')),
            ],
            options={
                'verbose_name': 'ProtocolIngredient',
                'db_table': 'protocol_ingredients',
            },
        ),
    ]
