# Generated by Django 4.2.1 on 2023-05-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_created_at_projects_updated_at'),
        ('protocols', '0008_alter_protocol_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='projects.projects'),
        ),
    ]
