# Generated by Django 4.2.1 on 2023-05-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_created_at_projects_updated_at'),
        ('protocols', '0009_protocol_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterUniqueTogether(
            name='protocol',
            unique_together={('name', 'project')},
        ),
    ]
