# Generated by Django 4.2.1 on 2023-06-04 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_created_at_projects_updated_at'),
        ('protocols', '0010_alter_protocol_name_alter_protocol_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='projects.projects'),
        ),
    ]
