# Generated by Django 4.2.1 on 2023-06-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0011_alter_protocol_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='extra',
            field=models.JSONField(null=True),
        ),
    ]
