# Generated by Django 4.2.1 on 2023-06-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0012_protocol_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='extra',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
