# Generated by Django 4.2.1 on 2023-06-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0014_protocol_ingredients_list_protocolsensorypanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolsensorypanel',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_sensory_panels', to='protocols.protocol'),
        ),
        migrations.AlterUniqueTogether(
            name='protocolsensorypanel',
            unique_together={('protocol', 'variable')},
        ),
    ]
