# Generated by Django 4.2.1 on 2023-07-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0016_protocol_aroma_intensity_protocol_nutrition_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='is_draft',
            field=models.SmallIntegerField(default=0),
        ),
    ]
