# Generated by Django 4.2.1 on 2023-05-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0004_alter_ingredientnode_ingredient'),
        ('protocols', '0001_initial'),
        ('meta_recipe', '0004_alter_metarecipe_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=225, unique=True)),
                ('meta_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_for_meta', to='meta_recipe.metarecipe')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_for_protocol', to='protocols.protocol')),
            ],
            options={
                'verbose_name': 'Recipe',
                'db_table': 'recipe',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=225)),
                ('amount', models.FloatField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='ingredients.ingredients')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipe')),
            ],
            options={
                'verbose_name': 'RecipeIngredient',
                'db_table': 'recipe_ingredients',
            },
        ),
    ]
