# Generated by Django 4.2.1 on 2023-05-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meta_recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('meta_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='meta_recipe.metarecipe')),
            ],
            options={
                'verbose_name': 'Recipe',
                'db_table': 'recipe',
            },
        ),
    ]
