# Generated by Django 4.2.1 on 2023-06-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='amount',
            new_name='quantity',
        ),
    ]
