# Generated by Django 4.2.1 on 2023-06-21 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipeprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('ingredient', 'ingredient'), ('process', 'process'), ('merge ', 'merge'), ('serve ', 'serve')], max_length=12, null=True)),
                ('model_id', models.BigIntegerField(null=True)),
                ('container', models.CharField(max_length=225, null=True)),
                ('slug', models.CharField(max_length=225, null=True)),
                ('payload', models.JSONField(null=True)),
                ('type', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_nodes', to='recipe.recipe')),
            ],
            options={
                'verbose_name': 'RecipeNode',
                'db_table': 'recipe_nodes',
            },
        ),
        migrations.CreateModel(
            name='RecipeEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_node_edges', to='recipe.recipenode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_node_edges', to='recipe.recipenode')),
            ],
            options={
                'verbose_name': 'RecipeEdge',
                'db_table': 'recipe_edges',
            },
        ),
    ]
