# Generated by Django 4.2.1 on 2023-05-10 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_alter_ingredientnode_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientnode',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node', to='ingredients.ingredients'),
        ),
    ]
