# Generated by Django 3.0.7 on 2020-07-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientofrecipe',
            name='value',
        ),
    ]
