# Generated by Django 3.0.7 on 2020-07-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20200714_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField()),
                ('name', models.CharField(max_length=30, null=True)),
                ('use_per_km', models.FloatField()),
            ],
        ),
    ]
