# Generated by Django 3.0.7 on 2020-07-19 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20200719_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlerecipe',
            name='metarecipe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_recipe', to='recipes.MetaRecipe'),
        ),
        migrations.AddField(
            model_name='singlerecipeingredient',
            name='single_recipe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_recipe_ingredients', to='recipes.SingleRecipe'),
        ),
        migrations.AlterField(
            model_name='singlerecipe',
            name='diet',
            field=models.CharField(choices=[('KOSHER', 'Kosher'), ('VEGAN', 'Vegan'), ('KETOGENIC', 'Ketogenic')], max_length=50),
        ),
    ]
