# Generated by Django 3.0.7 on 2020-08-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_delete_testrecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandUse',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='IngredientOfRecipe',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
