# Generated by Django 3.2.19 on 2023-06-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20200824_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlerecipeingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml')], default='G', max_length=8),
        ),
    ]
