# Generated by Django 4.2.1 on 2023-05-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0004_alter_ingredientnode_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('min', models.FloatField(null=True)),
                ('max', models.FloatField(null=True)),
                ('unit', models.CharField(blank=True, max_length=180, null=True)),
                ('dependent_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_meta_recipe', to='ingredients.ingredients')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_recipe', to='ingredients.ingredients')),
            ],
            options={
                'verbose_name': 'MetaRecipe',
                'db_table': 'meta_recipe',
            },
        ),
    ]
