# Generated by Django 4.2.1 on 2023-05-17 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredientnode_ingredient'),
        ('meta_recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metarecipe',
            name='dependent_ingredient',
        ),
        migrations.RemoveField(
            model_name='metarecipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='metarecipe',
            name='max',
        ),
        migrations.RemoveField(
            model_name='metarecipe',
            name='min',
        ),
        migrations.RemoveField(
            model_name='metarecipe',
            name='unit',
        ),
        migrations.AddField(
            model_name='metarecipe',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='MetaRecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('min', models.FloatField(null=True)),
                ('max', models.FloatField(null=True)),
                ('unit', models.CharField(blank=True, max_length=180, null=True)),
                ('dependent_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_meta_recipe_ingredient', to='ingredients.ingredients')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_recipe_ingredient', to='ingredients.ingredients')),
            ],
            options={
                'verbose_name': 'MetaRecipe Ingredients',
                'db_table': 'meta_recipe_ingredients',
            },
        ),
    ]
