# Generated by Django 4.2.1 on 2023-05-17 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta_recipe', '0002_remove_metarecipe_dependent_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metarecipeingredients',
            name='meta_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_recipe_parent', to='meta_recipe.metarecipe'),
        ),
    ]
