# Generated by Django 4.2.1 on 2023-05-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_recipe', '0003_metarecipeingredients_meta_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metarecipe',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='metarecipeingredients',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
