# Generated by Django 4.2.1 on 2023-05-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('meta_recipe', '0004_alter_metarecipe_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metarecipeingredients',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_recipe_project', to='projects.projects'),
        ),
    ]
