# Generated by Django 4.2.1 on 2023-06-21 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0013_alter_protocol_extra'),
        ('meta_recipe', '0006_remove_metarecipeingredients_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metarecipe',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='metarecipe',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='metarecipe',
            name='ingredient_constraints',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='metarecipe',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocol_meta_recipes', to='protocols.protocol'),
        ),
    ]
