# Generated by Django 3.0.7 on 2020-08-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20200719_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlerecipeingredient',
            name='unit',
            field=models.CharField(choices=[('KG', 'kg'), ('G', 'g'), ('L', 'l'), ('ML', 'ml')], default='G', max_length=8),
        ),
        migrations.AddField(
            model_name='singlerecipeingredient',
            name='unit_convertor_g',
            field=models.FloatField(default=0.001),
        ),
    ]
