# Generated by Django 3.0.7 on 2020-08-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20200811_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('entity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('taste_name', models.CharField(max_length=50, null=True)),
                ('sweet', models.FloatField(default=0.0)),
                ('salty', models.FloatField(default=0.0)),
                ('sour', models.FloatField(default=0.0)),
                ('bitter', models.FloatField(default=0.0)),
                ('umami', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
            ],
        ),
    ]
