# Generated by Django 3.0.7 on 2020-08-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_environmentalimpact'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(default='dish', max_length=32),
        ),
    ]
