# Generated by Django 3.0.7 on 2020-07-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_testrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientOfRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField()),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
