# Generated by Django 3.0.7 on 2020-08-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_taste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlerecipeingredient',
            name='max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='singlerecipeingredient',
            name='min',
            field=models.FloatField(default=0.0),
        ),
    ]
