# Generated by Django 4.2.1 on 2023-05-11 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Molecules',
                'verbose_name_plural': 'Molecules',
            },
        ),
        migrations.CreateModel(
            name='MoleculesNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('molecule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node', to='molecules.molecules')),
            ],
        ),
    ]
