# Generated by Django 4.2.1 on 2023-06-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensory_panels', '0002_sensorypanel_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorypanel',
            old_name='data',
            new_name='date',
        ),
    ]
