# Generated by Django 4.2.1 on 2023-06-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensory_panels', '0003_rename_data_sensorypanel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractSensoryPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
            ],
            options={
                'verbose_name': 'AbstractSensoryPanel',
                'db_table': 'abstract_sensory_panels',
            },
        ),
    ]
