# Generated by Django 4.2.1 on 2023-06-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_created_at_projects_updated_at'),
        ('sensory_panels', '0004_abstractsensorypanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorypanel',
            name='panel_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='sensorypanel',
            unique_together={('panel_variable', 'project')},
        ),
    ]
