# Generated by Django 4.2.1 on 2023-05-14 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0004_alter_ingredientnode_ingredient'),
        ('molecules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientMolecules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_concentration_min', models.FloatField(blank=True, null=True)),
                ('mass_concentration_max', models.FloatField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredientOpj', to='ingredients.ingredientnode')),
                ('molecules', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moleculesOpj', to='molecules.moleculesnode')),
            ],
        ),
    ]
