# Generated by Django 4.2.1 on 2023-05-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meta_recipe', '0006_remove_metarecipeingredients_project_and_more'),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('metaRecipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metarecipe_sample_descriptions', to='meta_recipe.metarecipe')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_sample_descriptions', to='recipe.recipe')),
            ],
        ),
    ]
