# Generated by Django 4.2.1 on 2023-05-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=255, unique=True)),
                ('uniprot_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sensory_qualities', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
