# Generated by Django 3.0.7 on 2020-07-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20200714_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipe', to='recipes.IngredientOfRecipe'),
        ),
    ]
