# Generated by Django 3.0.7 on 2020-07-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_landuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SingleRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('diet', models.CharField(choices=[('KOHSER', 'Kohser'), ('VEGAN', 'Vegan'), ('KETOGENIC', 'Ketogenic')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SingleRecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField()),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='landuse',
            name='use_per_km',
            field=models.FloatField(default=0),
        ),
    ]
