# Generated by Django 4.2.1 on 2023-05-17 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, choices=[('time', 'Time'), ('choices', 'choices')], max_length=50, null=True)),
                ('options', models.JSONField(null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('next_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='process', to='process.process')),
            ],
            options={
                'verbose_name': 'Process',
                'db_table': 'processes',
            },
        ),
    ]
