# Generated by Django 4.2.1 on 2023-05-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_alter_process_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'Process'},
        ),
        migrations.AlterField(
            model_name='process',
            name='options',
            field=models.JSONField(null=True),
        ),
        migrations.AlterModelTable(
            name='process',
            table='processes',
        ),
    ]
