# Generated by Django 4.2.1 on 2023-05-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_alter_process_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='process',
            name='next_process',
        ),
        migrations.RemoveField(
            model_name='process',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='process',
            name='type',
            field=models.CharField(blank=True, choices=[('time', 'Time'), ('choices', 'choices')], max_length=50, null=True),
        ),
    ]
