# Generated by Django 4.2.1 on 2023-05-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_remove_process_duration_remove_process_next_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
