# Generated by Django 3.0.7 on 2020-08-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20200816_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalImpact',
            fields=[
                ('entity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('land_use', models.FloatField(default=0.0)),
                ('ghg_emissions', models.FloatField(default=0.0)),
                ('acidifying_emissions', models.FloatField(default=0.0)),
                ('eutrophying_emissions', models.FloatField(default=0.0)),
                ('freshwater_withdrawals', models.FloatField(default=0.0)),
                ('stress_weighted_water_use', models.FloatField(default=0.0)),
            ],
        ),
    ]
