# Generated by Django 4.2.1 on 2023-05-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
                ('type', models.CharField(choices=[('cooking', 'cooking'), ('sensor', 'sensor')], default='cooking', max_length=225)),
            ],
            options={
                'verbose_name': 'Equipment',
                'db_table': 'equipments',
            },
        ),
    ]
