# Generated by Django 4.2.1 on 2023-05-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_created_at_projects_updated_at'),
        ('equipments', '0002_equipment_brand_equipment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='projects.projects'),
        ),
    ]
