# Generated by Django 4.2.1 on 2023-05-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_created_at_projects_updated_at'),
        ('sensors', '0002_sensors_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='sensors',
            unique_together={('name', 'project')},
        ),
    ]
